"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DISALLOWED_BUYS = exports.SUGGESTIONS_AND_COMMENTS = exports.ROOKIE_PICK_COMMENTS = exports.TE_RANK = exports.WR_RANK = exports.RB_RANK = exports.QB_RANK = exports.POSITIONAL_GRADES = exports.FALLER_VALUES = exports.RISER_VALUES = exports.FALLERS = exports.RISERS = exports.HOLDS = exports.PLUS_MAP = exports.BUYS = exports.SELLS = exports.TEAM_NAME = exports.LEAGUE_SIZE = exports.NON_SLEEPER_IDS = exports.COMMENTS = exports.WAIVER_TARGETS = exports.STARTING_LINEUP = exports.POSITIONAL_GRADE_OVERRIDES = exports.REBUILD_CONTEND_VALUE = exports.DRAFT_CAPITAL_VALUE = exports.DRAFT_CAPITAL_NOTES = exports.IN_RETURN = exports.PLAYERS_TO_TRADE = exports.CORNERSTONES = exports.DEPTH_SCORE_OVERRIDE = exports.OUTLOOK = exports.ARCHETYPE = exports.PLAYERS_TO_TARGET = exports.OTHER_SETTINGS = exports.MODULE = exports.TEAM_CODE = exports.PLAYER_ID = exports.NONE_TEAM_ID = exports.USER_ID = exports.TEAM_ID = exports.LEAGUE_ID = void 0;
exports.LEAGUE_ID = 'leagueId';
exports.TEAM_ID = 'teamId';
exports.USER_ID = 'userId';
exports.NONE_TEAM_ID = 'none';
exports.PLAYER_ID = 'playerId';
exports.TEAM_CODE = 'teamCode';
exports.MODULE = 'module';
exports.OTHER_SETTINGS = 'otherSettings';
exports.PLAYERS_TO_TARGET = 'playersToTarget';
exports.ARCHETYPE = 'archetype';
exports.OUTLOOK = 'outlook';
exports.DEPTH_SCORE_OVERRIDE = 'depthScoreOverride';
exports.CORNERSTONES = 'cornerstones';
exports.PLAYERS_TO_TRADE = 'playersToTrade';
exports.IN_RETURN = 'inReturn';
exports.DRAFT_CAPITAL_NOTES = 'draftCapitalNotes';
exports.DRAFT_CAPITAL_VALUE = 'draftCapitalValue';
exports.REBUILD_CONTEND_VALUE = 'rebuildContendValue';
exports.POSITIONAL_GRADE_OVERRIDES = 'positionalGradeOverrides';
exports.STARTING_LINEUP = 'startingLineup';
exports.WAIVER_TARGETS = 'waiverTargets';
exports.COMMENTS = 'comments';
exports.NON_SLEEPER_IDS = 'nonSleeperIds';
exports.LEAGUE_SIZE = 'leagueSize';
exports.TEAM_NAME = 'teamName';
// v2 params
exports.SELLS = 'sells';
exports.BUYS = 'buys';
exports.PLUS_MAP = 'plusMap';
exports.HOLDS = 'holds';
exports.RISERS = 'risers';
exports.FALLERS = 'fallers';
exports.RISER_VALUES = 'riserValues';
exports.FALLER_VALUES = 'fallerValues';
exports.POSITIONAL_GRADES = 'posGrades';
exports.QB_RANK = 'qbRank';
exports.RB_RANK = 'rbRank';
exports.WR_RANK = 'wrRank';
exports.TE_RANK = 'teRank';
exports.ROOKIE_PICK_COMMENTS = 'rookieComments';
exports.SUGGESTIONS_AND_COMMENTS = 'suggestions';
// Infinite
exports.DISALLOWED_BUYS = 'disallowedBuys';
